# Generated by Django 4.2.4 on 2023-08-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='invitationcode',
            old_name='activated_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated_by',
            field=models.ManyToManyField(blank=True, related_name='activated_users', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
