# Generated by Django 4.2.4 on 2023-08-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_invitationcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
