# Generated by Django 4.2.4 on 2023-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_invitationcode_is_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activated_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
